Topic/nginx base
mgit-at/ansible-collection-roles pull request #54
Opened 2024-02-15 14:28 UTC by ohdearaugustin

Add nginx_base role to collection.

2024-02-15 16:18 UTC, ohdearaugustin commented
Blocked by #52

2024-02-19 13:17 UTC, MarkusTeufelberger commented on roles/apt_repo_ubuntu_nginx/tasks/main.yml
> +    - name: Add docker apt repo
docker --> nginx

2024-02-19 14:07 UTC, MarkusTeufelberger requested changes
reviewed nginx_base

2024-02-19 14:07 UTC, MarkusTeufelberger commented on roles/nginx_base/tasks/main.yml
> +  when: nginx_base_conf_d_files is defined
this is a default var

2024-02-19 14:07 UTC, MarkusTeufelberger commented on roles/nginx_base/tasks/main.yml
> +  when: nginx_base_conf_d_files is defined
len > 0?

2024-02-19 14:07 UTC, MarkusTeufelberger commented on roles/nginx_base/tasks/main.yml
> +  when: nginx_base_snippets is defined
see above

2024-02-19 15:26 UTC, ohdearaugustin commented on roles/nginx_base/molecule/nginx-extras/verify.yml
> +    - name: Check if nginx is installed
next time

2024-02-19 15:38 UTC, ohdearaugustin commented on roles/nginx_base/files/snippets/tls.conf
> +ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES12
Regenerated with nginx and openssl version from Debian 10 as this is the oldest OS we use.

2024-02-19 18:50 UTC, merged